/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NotFoundImport } from './routes/not-found'
import { Route as LinkIdImport } from './routes/$linkId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const NotFoundRoute = NotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRoute,
} as any)

const LinkIdRoute = LinkIdImport.update({
  id: '/$linkId',
  path: '/$linkId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$linkId': {
      id: '/$linkId'
      path: '/$linkId'
      fullPath: '/$linkId'
      preLoaderRoute: typeof LinkIdImport
      parentRoute: typeof rootRoute
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$linkId': typeof LinkIdRoute
  '/not-found': typeof NotFoundRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$linkId': typeof LinkIdRoute
  '/not-found': typeof NotFoundRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$linkId': typeof LinkIdRoute
  '/not-found': typeof NotFoundRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$linkId' | '/not-found'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$linkId' | '/not-found'
  id: '__root__' | '/' | '/$linkId' | '/not-found'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinkIdRoute: typeof LinkIdRoute
  NotFoundRoute: typeof NotFoundRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinkIdRoute: LinkIdRoute,
  NotFoundRoute: NotFoundRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$linkId",
        "/not-found"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$linkId": {
      "filePath": "$linkId.tsx"
    },
    "/not-found": {
      "filePath": "not-found.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
